// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahrvzanlllsxgxbxwmuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFocnZ6YW5sbGxzeGd4Ynh3bXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTcxOTgsImV4cCI6MjA3MTY5MzE5OH0.QDO8GCeG_mSFZBO6C_kPh1S6bU_l5PqKEYrhCH39ems";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});